"""add messages in db

Revision ID: 0046f3f5e6d0
Revises: 9ad8b1b6d50c
Create Date: 2026-06-18 08:51:22.736909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0046f3f5e6d0'
down_revision: Union[str, None] = '9ad8b1b6d50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('start_message', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('help_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'help_message')
    op.drop_column('settings', 'start_message')
    # ### end Alembic commands ###
