"""add for bot

Revision ID: 11911f5754d6
Revises: 81ba17851e79
Create Date: 2026-06-16 08:44:09.563781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11911f5754d6'
down_revision: Union[str, None] = '81ba17851e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('for_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'for_bot')
    # ### end Alembic commands ###
