"""add settings table

Revision ID: 488ad8af6c70
Revises: 11911f5754d6
Create Date: 2026-06-17 00:50:19.620845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "488ad8af6c70"
down_revision: Union[str, None] = "11911f5754d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price_per_gb", sa.Integer(), nullable=True, server_default="5000"),
        sa.Column("start_price", sa.Integer(), nullable=True, server_default="100000"),
        sa.Column(
            "minimum_purchase_amount",
            sa.Integer(),
            nullable=True,
            server_default="500000",
        ),
        sa.Column("registration_enabled", sa.Boolean(), nullable=True),
        sa.Column("payment_enabled", sa.Boolean(), nullable=True),
        sa.Column("card_number", sa.String(length=50), nullable=True),
        sa.Column("card_holder", sa.String(length=100), nullable=True),
        sa.Column("wallet_address", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("""
        INSERT INTO settings (
            id,
            price_per_gb,
            start_price,
            minimum_purchase_amount,
            registration_enabled,
            payment_enabled
        )
        VALUES (
            1,
            5000,
            100000,
            500000,
            true,
            true
        )
    """)
    op.create_index(op.f("ix_settings_id"), "settings", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_settings_id"), table_name="settings")
    op.drop_table("settings")
    # ### end Alembic commands ###
