"""Change inbound id type

Revision ID: b8adda3a1e58
Revises: 09d396b4dcf7
Create Date: 2026-05-26 23:04:29.111303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8adda3a1e58'
down_revision: Union[str, None] = '09d396b4dcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("admins") as batch_op:
        batch_op.alter_column(
            "inbound_id",
            existing_type=sa.Integer(),
            type_=sa.String(),
            existing_nullable=True,
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'inbound_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
